<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);MarkupEditor.Tests\**\*</DefaultItemExcludes>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>MarkupEditor</RootNamespace>
    <AssemblyName>MarkupEditor</AssemblyName>
    <ApplicationIcon>Properties\images.ico</ApplicationIcon>
    <Deterministic>true</Deterministic>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
	<ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
	<ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
	<ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.37.0" />
    <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="MarkupEditor.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="FindReplaceDialog.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <EmbeddedResource Update="MarkupEditor.resx">
      <DependentUpon>MarkupEditor.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Include="Assets\app.ico" />
    <None Include="Assets\app-icon-source.png" />
    <None Include="Assets\ICON_ATTRIBUTION.txt" />
    <Content Include="Properties\images.ico" />
  </ItemGroup>
</Project>
