//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may be incorrect if regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkupEditor.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        private static Settings defaultInstance =
            ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LivePreviewEnabled
        {
            get
            {
                return ((bool)(this["LivePreviewEnabled"]));
            }
            set
            {
                this["LivePreviewEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WordWrap
        {
            get
            {
                return ((bool)(this["WordWrap"]));
            }
            set
            {
                this["WordWrap"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public float EditorFontSize
        {
            get
            {
                return ((float)(this["EditorFontSize"]));
            }
            set
            {
                this["EditorFontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("480")]
        public int SplitterDistance
        {
            get
            {
                return ((int)(this["SplitterDistance"]));
            }
            set
            {
                this["SplitterDistance"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasSavedWindowLayout
        {
            get
            {
                return ((bool)(this["HasSavedWindowLayout"]));
            }
            set
            {
                this["HasSavedWindowLayout"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 884, 561")]
        public global::System.Drawing.Rectangle MainWindowBounds
        {
            get
            {
                return ((global::System.Drawing.Rectangle)(this["MainWindowBounds"]));
            }
            set
            {
                this["MainWindowBounds"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainWindowState
        {
            get
            {
                return ((int)(this["MainWindowState"]));
            }
            set
            {
                this["MainWindowState"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecentDocuments
        {
            get
            {
                return ((string)(this["RecentDocuments"]));
            }
            set
            {
                this["RecentDocuments"] = value;
            }
        }
    }
}
